/**
 * Generate `src/host/prompts.js` from the extracted WorkBuddy enhance-prompt assets.
 *
 * The assets are copied, never authored: `PRD §6.5` fixes them to the runtime
 * constants of WorkBuddy's main process. This script emits them as
 * `JSON.stringify` string literals so that backticks, `${`, or any other
 * template-literal metacharacter in the source text cannot corrupt the copy.
 *
 * Usage:
 *   node scripts/gen-prompts.mjs <path-to-enhance_prompts.json>
 *   node scripts/gen-prompts.mjs --self-check      # regenerate in memory and compare to src
 *
 * @module dsh-prompt-enhance/scripts/gen-prompts
 */

import { existsSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const PLUGIN_ROOT = resolve(HERE, '..')
const TARGET = resolve(PLUGIN_ROOT, 'src/host/prompts.js')

/**
 * Ordered candidate paths for the extracted prompt assets.
 *
 * The probe writes them to the *workspace*'s `tmp/`, which is not necessarily an
 * ancestor of the plugin — after the 2026-09-14 20:53 relocation the plugin lives
 * in `D:\Ruanjian\dsh-plugins\` while the workspace stayed at
 * `D:\Ruanjian\DeepSeekHarness\`. A fixed `../../../../` therefore resolved to
 * `D:\tmp\` and ENOENTed, so the depth is now discovered instead of assumed.
 * `PROMPT_ASSETS` overrides everything.
 * @returns candidate paths, best first.
 */
function sourceCandidates() {
  const bare = 'tmp/enhance_prompts.json'
  return [
    process.env.PROMPT_ASSETS,
    resolve(PLUGIN_ROOT, bare),
    /* workspace is a sibling of the plugin directory (current layout) */
    resolve(PLUGIN_ROOT, '../../DeepSeekHarness', bare),
    /* workspace is the plugin's grandparent (plugins/ inside the workspace) */
    resolve(PLUGIN_ROOT, '../../', bare),
    /* historical layout: <workspace>/app/resources/internal-plugins/<plugin>/ */
    resolve(PLUGIN_ROOT, '../../../../', bare),
  ].filter((candidate) => typeof candidate === 'string' && candidate.length > 0)
}

const DEFAULT_SOURCE = sourceCandidates().find((candidate) => existsSync(candidate))
  ?? resolve(PLUGIN_ROOT, '../../../../', 'tmp/enhance_prompts.json')

/** sha256 (lowercase hex, first 16 chars) of one asset after LF normalisation. */
function digest(text) {
  return createHash('sha256').update(Buffer.from(text, 'utf8')).digest('hex').slice(0, 16)
}

/** Normalise CRLF to LF so the copy is byte-identical regardless of the extraction host. */
function normalize(text) {
  return text.replace(/\r\n/gu, '\n').replace(/\r/gu, '\n')
}

/**
 * Read the extracted asset pair.
 * @param sourcePath - path to the JSON emitted by the WorkBuddy asar probe.
 * @returns the LF-normalised system prompt and user template.
 */
async function readAssets(sourcePath) {
  const raw = JSON.parse(await readFile(sourcePath, 'utf8'))
  const system = raw.DEFAULT_ENHANCE_PROMPT_SYSTEM_TEMPLATE
  const user = raw.DEFAULT_ENHANCE_PROMPT_USER_TEMPLATE
  if (typeof system !== 'string' || typeof user !== 'string') {
    throw new Error(`${sourcePath}: expected DEFAULT_ENHANCE_PROMPT_{SYSTEM,USER}_TEMPLATE strings`)
  }
  return { system: normalize(system), user: normalize(user) }
}

/** Render the module body for one asset pair. */
function render(system, user) {
  return `/**
 * WorkBuddy 「增强提示词」prompt assets — verbatim copies, not authored text.
 *
 * Source: WorkBuddy main-process constants \`DEFAULT_ENHANCE_PROMPT_SYSTEM_TEMPLATE\`
 * and \`DEFAULT_ENHANCE_PROMPT_USER_TEMPLATE\` (identical line-for-line to the
 * remote-delivered \`prompts[118]\` of \`acc-product-config-v3.json\`; only the line
 * terminator differed, CRLF remote vs LF constant).
 *
 * Generated by \`scripts/gen-prompts.mjs\` — do not hand-edit.
 * \`scripts/verify-prompts.mjs\` fails the build when either digest drifts.
 *
 * | asset         | lines | chars | sha256 (first 16, LF-normalised) |
 * |---------------|-------|-------|----------------------------------|
 * | system prompt | ${String(system.split('\n').length).padEnd(5)} | ${String(system.length).padEnd(5)} | \`${digest(system)}\`                   |
 * | user template | ${String(user.split('\n').length).padEnd(5)} | ${String(user.length).padEnd(5)} | \`${digest(user)}\`                   |
 *
 * The user template carries exactly one placeholder, \`{input}\`, replaced by the
 * caller's draft through {@link renderUserPrompt}.
 *
 * @module dsh-prompt-enhance/prompts
 */

/** Digest anchors, asserted by the prompt verifier and the unit suite. */
export const PROMPT_DIGESTS = Object.freeze({
  system: '${digest(system)}',
  user: '${digest(user)}',
})

/** The placeholder the user template expects exactly once. */
export const USER_TEMPLATE_PLACEHOLDER = '{input}'

/** System prompt handed to the model as the request's \`system\` slot. */
export const SYSTEM_PROMPT = ${JSON.stringify(system)}

/** User-message template; \`{input}\` is replaced by the raw draft. */
export const USER_TEMPLATE = ${JSON.stringify(user)}

/**
 * Substitute the draft into the user template, literally.
 *
 * The template itself is copied verbatim; only the substitution is our own.
 * The original does \`USER_TEMPLATE.replace('{input}', input)\`, and a string
 * replacement expands \`$&\`, \`$'\`, \`$\\\`\` and \`$1\` — so a draft containing any of
 * those would silently inject parts of the template into the prompt. Splitting
 * on the placeholder is a literal join with identical behaviour for every
 * ordinary draft and correct behaviour for the rest.
 * @param input - the raw draft text.
 * @returns the complete user message content.
 */
export function renderUserPrompt(input) {
  return USER_TEMPLATE.split(USER_TEMPLATE_PLACEHOLDER).join(input)
}
`
}

const [, , argument] = process.argv
const autoSource = argument === undefined || argument === '--self-check'
const sourcePath = autoSource ? DEFAULT_SOURCE : argument

if (autoSource && !existsSync(sourcePath)) {
  console.error('gen-prompts: cannot find the extracted prompt assets.')
  console.error('  pass the path explicitly:  node scripts/gen-prompts.mjs <path-to-enhance_prompts.json>')
  console.error('  or set PROMPT_ASSETS=<path>')
  console.error('  tried:')
  for (const candidate of sourceCandidates()) console.error(`    ${candidate}`)
  process.exit(1)
}

const { system, user } = await readAssets(sourcePath)
const rendered = render(system, user)

if (argument === '--self-check') {
  const current = await readFile(TARGET, 'utf8').catch(() => '')
  if (current !== rendered) {
    console.error('gen-prompts: src/host/prompts.js is stale — rerun without --self-check')
    process.exit(1)
  }
  console.log(`gen-prompts: up to date (system ${digest(system)}, user ${digest(user)})`)
} else {
  await writeFile(TARGET, rendered, 'utf8')
  console.log(`gen-prompts: wrote ${TARGET}`)
  console.log(`  system: ${system.split('\n').length} lines / ${system.length} chars / ${digest(system)}`)
  console.log(`  user:   ${user.split('\n').length} lines / ${user.length} chars / ${digest(user)}`)
}
